# SPDX-License-Identifier: MPL-2.0
# mise.toml — pinned toolchain for Skein.jl (a pure-Julia library).
# Only tools this repo actually uses; nothing here serves a foreign toolchain.

[tools]
julia = "1.10"
just = "1.25"
shellcheck = "latest"

[env]
JULIA_PROJECT = "@."
